services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000
  website:
    image: nginx:alpine
    volumes:
      - ./website:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
