# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: API smoke tests
        run: |
          python - << 'PY'
          import importlib.util
          spec = importlib.util.spec_from_file_location("app", "backend/app.py")
          mod = importlib.util.module_from_spec(spec)
          spec.loader.exec_module(mod)
          assert hasattr(mod, "app"), "FastAPI app not found"
          print("App import OK")
          PY
